#!/usr/bin/env node
/**
 * Finish the kinnovationgroup.com build.
 *
 * `public/` is shared between both sites, so the standalone build inherits
 * kinjalpandey.com's CNAME, robots.txt and sitemap.xml. Left alone, GitHub
 * Pages would try to serve the second site on the first site's domain. This
 * rewrites the three files that must differ, and strips the assets that only
 * belong to the main site.
 *
 * Written in Node rather than Python on purpose: the build already requires
 * Node, and Windows has no `python3` on PATH by default. When this was a
 * Python script it failed silently after a successful `ng build`, leaving a
 * dist folder that looked finished but carried the wrong domain.
 *
 * Run automatically by `npm run build:kinnovation`.
 */

import { existsSync, mkdirSync, readFileSync, rmSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(REPO, 'dist', 'kinnovation', 'browser');
const SITE = join(REPO, 'src', 'app', 'data', 'site.kinnovation.ts');

/** Read the second site's origin from its own config, so they cannot drift. */
function origin(src) {
  const m = src.match(/export const ORIGIN = '([^']+)'/);
  if (!m) throw new Error('No ORIGIN found in site.kinnovation.ts');
  return m[1];
}

/** Root, then one entry per venture slug. */
function routes(src) {
  const slugs = [...src.matchAll(/\['([a-z][a-z-]*)', '/g)].map((m) => m[1]);
  return [['', 1.0], ...slugs.map((s) => [s, 0.7])];
}

async function dirSize(dir) {
  let total = 0;
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    total += entry.isDirectory() ? await dirSize(full) : statSync(full).size;
  }
  return total;
}

async function main() {
  if (!existsSync(DIST)) {
    console.error(`No build at ${DIST}. Run \`ng build --configuration kinnovation\` first.`);
    process.exitCode = 1;
    return;
  }

  const src = readFileSync(SITE, 'utf8');
  const ORIGIN = origin(src);
  const host = ORIGIN.replace('https://', '');
  const pages = routes(src);

  writeFileSync(join(DIST, 'CNAME'), host + '\n');

  writeFileSync(
    join(DIST, 'robots.txt'),
    [
      '# GENERATED by tools/kinnovation-dist.mjs',
      'User-agent: *',
      'Disallow: /docs/',
      'Allow: /',
      '',
      `Sitemap: ${ORIGIN}/sitemap.xml`,
      '',
    ].join('\n'),
  );

  const urls = pages
    .map(
      ([p, pr]) =>
        `  <url>\n    <loc>${ORIGIN}/${p}</loc>\n` +
        `    <changefreq>monthly</changefreq>\n    <priority>${pr}</priority>\n  </url>`,
    )
    .join('\n');
  writeFileSync(
    join(DIST, 'sitemap.xml'),
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
      `${urls}\n</urlset>\n`,
  );

  // Documents and the modelling library belong to the personal site only.
  // Shipping them here would duplicate ~14 MB and put the portfolio on a
  // domain that has nothing to do with it.
  for (const rel of ['docs', 'img/model', 'img/certs', 'img/logos', 'img/tiles', 'resume']) {
    rmSync(join(DIST, rel), { recursive: true, force: true });
  }

  // Angular emits the source-named index alongside index.html whenever the
  // `index` option is not literally index.html. Harmless, but it would be
  // served at /index.kinnovation.html.
  const stray = join(DIST, 'index.kinnovation.html');
  if (existsSync(stray)) unlinkSync(stray);

  writeFileSync(join(DIST, '.nojekyll'), '');

  const size = await dirSize(DIST);
  console.log(`  CNAME        ${host}`);
  console.log(`  sitemap.xml  ${pages.length} URLs`);
  console.log('  pruned       docs, model, certs, logos, tiles, resume');
  console.log(`  size         ${(size / 1e6).toFixed(1)} MB`);
}

main();
