#!/usr/bin/env python3
"""
Generate sitemap.xml, robots.txt, CNAME and the web manifest from the single
source of truth in `src/app/data/site.ts`.

Run after adding or renaming a route:

    python3 tools/seo.py

Everything is keyed off ORIGIN in site.ts, so changing the domain there is
enough — nothing else hardcodes it.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SITE_TS = REPO / "src" / "app" / "data" / "site.ts"
PUBLIC = REPO / "public"


def read_site() -> tuple[str, list[tuple[str, float]]]:
    src = SITE_TS.read_text()
    origin = re.search(r"export const ORIGIN = '([^']+)'", src).group(1)

    # PAGES entries pair a path with a priority.
    paths = re.findall(r"path: '([^']*)',\n\s+title:", src)
    priorities = [float(x) for x in re.findall(r"priority: ([0-9.]+),", src)]
    entries = list(zip(paths, priorities))

    # VENTURE_PAGES are generated from a table of slugs.
    ventures = re.findall(r"\['([a-z][a-z-]*)', '", src)
    entries += [(f"entrepreneur/{slug}", 0.6) for slug in ventures]
    return origin, entries


def write_sitemap(origin: str, entries: list[tuple[str, float]]) -> None:
    urls = "\n".join(
        f"  <url>\n"
        f"    <loc>{origin}/{path}</loc>\n"
        f"    <changefreq>monthly</changefreq>\n"
        f"    <priority>{priority}</priority>\n"
        f"  </url>"
        for path, priority in entries
    )
    (PUBLIC / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- GENERATED by tools/seo.py — do not hand-edit. -->\n"
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{urls}\n"
        "</urlset>\n"
    )


def write_robots(origin: str) -> None:
    """
    NOTE: the /docs/ rule is load-bearing.

    Transcripts and certificates are reachable from the site but must not be
    indexed. This is a request rather than access control — anything that
    genuinely must stay private should not be published at all.
    """
    (PUBLIC / "robots.txt").write_text(
        "# GENERATED by tools/seo.py — do not hand-edit.\n"
        "\n"
        "# Transcripts and certificates are reachable from the site but should\n"
        "# not be indexed or surfaced in search. Honoured by Google, Bing and\n"
        "# other major crawlers — it is a request, not access control.\n"
        "\n"
        "User-agent: *\n"
        "Disallow: /docs/\n"
        "Allow: /\n"
        "\n"
        "# AI crawlers that honour robots.txt. Change Allow to Disallow on any\n"
        "# of these to opt out of that one.\n"
        "User-agent: GPTBot\n"
        "Disallow: /docs/\n"
        "Allow: /\n"
        "\n"
        "User-agent: ClaudeBot\n"
        "Disallow: /docs/\n"
        "Allow: /\n"
        "\n"
        f"Sitemap: {origin}/sitemap.xml\n"
    )


def write_cname(origin: str) -> None:
    """GitHub Pages reads this file to serve the custom domain."""
    (PUBLIC / "CNAME").write_text(origin.replace("https://", "").replace("http://", "") + "\n")


def write_manifest() -> None:
    (PUBLIC / "site.webmanifest").write_text(
        json.dumps(
            {
                "name": "Kinjal Pandey",
                "short_name": "Kinjal Pandey",
                "description": "Developer, entrepreneur, model.",
                "start_url": "/",
                "display": "standalone",
                "background_color": "#08080a",
                "theme_color": "#08080a",
                "icons": [
                    {"src": "favicon.ico", "sizes": "48x48", "type": "image/x-icon"}
                ],
            },
            indent=1,
        )
        + "\n"
    )


def main() -> int:
    origin, entries = read_site()
    write_sitemap(origin, entries)
    write_robots(origin)
    write_cname(origin)
    write_manifest()
    print(f"origin        {origin}")
    print(f"sitemap.xml   {len(entries)} URLs")
    print("robots.txt    /docs/ disallowed, sitemap referenced")
    print(f"CNAME         {origin.split('//')[1]}")
    print("site.webmanifest written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
